[package]
name = "ethash"
description = "An Apache-licensed Ethash implementation."
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
license = "Apache-2.0"

[dependencies]
etcommon-bigint = "0.2"
etcommon-rlp = "0.2"
sha3 = "0.6"
